### ISSUE TITLE
Insufficient instructions in README

### ISSUE THREAD

**Issue by 0Aditya-Singhal0** [vinhnx/VT.ai#1]
This repo is amazing in how it works right out of the box. However, I had some initial impressions that I would like to point out.

1. The setup is very OpenAI dependent. Would suggest putting it in README to tell users to configure it and change it before running. (Bonus if you make it an argument/ config param to change)
2. When I wanted to run it on Ollama, I didn't get any results because I didn't have ollama in my system :P which may seem very obvious but it would be great if you could put references/ instructions to aid first-timers. (recommend linking to the Ollama git repo since they have excellent instructions).

**Comment by vinhnx** [comment]
Thank you, @0Aditya-Singhal0!

Firstly, I would like to apologize for my late response. I am still new to Python and LLMs applied AI, so I was trying to learn every day m, hence my setup instructions are still vague and opaque, so I deeply appreciate any suggestions like yours. 

I will improve the README further base on your recommendations. 

Thank you again, and have a great day! 🍀

**Comment by vinhnx** [comment]
I have updated and improved README, I will improve it more in the future https://github.com/vinhnx/VT.ai/commit/b52fc3a64ede32e6683d87800ceb24224580bce0

Thank you!

**Comment by 0Aditya-Singhal0** [comment]
Lemme know if you want to collaborate since I am also working on similar things ;)
